version: 2
jobs:
  test:
    working_directory: ~/circulate
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker client
          command: |
            DOCKER_CLIENT_VERSION="17.11.0-ce"
            curl --location --output /tmp/docker-$DOCKER_CLIENT_VERSION.tgz https://download.docker.com/linux/static/edge/x86_64/docker-$DOCKER_CLIENT_VERSION.tgz
            tar --extract --gzip --directory /tmp -f /tmp/docker-$DOCKER_CLIENT_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build docker image
          command: docker build --tag petrpliska/kiwi-entrytask:latest --no-cache .
      - run:
          name: Install Goss and Dgoss
          command: |
            GOSS_VERSION="0.3.5"
            curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
            curl -L https://raw.githubusercontent.com/aelsabbahy/goss/v$GOSS_VERSION/extras/dgoss/dgoss -o /usr/local/bin/dgoss
            chmod +rx /usr/local/bin/goss
            chmod +rx /usr/local/bin/dgoss
      - run:
          name: Test docker image
          command: dgoss run petrpliska/kiwi-entrytask:latest
          environment:
            GOSS_FILES_STRATEGY: cp

workflows:
  version: 2
  release-image:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/

